### ISSUE TITLE
VCF preprocessor TypeError "can only join an iterable"

### ISSUE THREAD

**Issue by flaviahodel** [PharmGKB/PharmCAT#117]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
The VCF preprocessor script crashes when executed. I have tried using the tutorial material (samples and scripts) provided on GitHub for multi-sample VCF. I get the following output and error messages:

```
Saving output to results/pharmcat_ready/
Downloading from "https://zenodo.org/record/7251599/files/GRCh38_reference_fasta.tar"
	to "results/pharmcat_ready/GRCh38_reference_fasta.tar"

Downloaded to results/pharmcat_ready/reference.fna.bgz

Processing data/PharmCAT_tutorial_get-rm_wgs_30x_grch38.vcf.bgz
Generating index (data/PharmCAT_tutorial_get-rm_wgs_30x_grch38.vcf.bgz.csi)
Extracting PGx regions and modifying chromosome names for data/PharmCAT_tutorial_get-rm_wgs_30x_grch38.vcf.bgz.
Generating index (results/pharmcat_ready/PharmCAT_tutorial_get-rm_wgs_30x_grch38.pgx_regions.vcf.bgz.csi)
Normalizing VCF
Generating index (results/pharmcat_ready/PharmCAT_tutorial_get-rm_wgs_30x_grch38.pgx_regions.normalized.vcf.bgz.csi)
Preparing the reference PGx VCF
Generating index (results/pharmcat_ready/tmpsua5vxueextract_pgx_variants/pharmcat_positions.uniallelic.vcf.bgz.csi)
Retaining PGx positions, regardless of alleles
Generating index (results/pharmcat_ready/tmpsua5vxueextract_pgx_variants/PharmCAT_tutorial_get-rm_wgs_30x_grch38.pgx_regions.normalized.pgx_pos_only.vcf.bgz.csi)
Updating VCF header and PGx position annotations
Traceback (most recent call last):
  File "/Users/fl3567/Documents/PGx/PharmCAT/tutorial/preprocessor/PharmCAT_VCF_Preprocess.py", line 245, in <module>
    run(args)
  File "/Users/fl3567/Documents/PGx/PharmCAT/tutorial/preprocessor/PharmCAT_VCF_Preprocess.py", line 179, in run
    vcf_normalized_pgx_only = util.filter_pgx_variants(bcftools_path, bgzip_path, vcf_normalized, reference_genome,
  File "/Users/fl3567/Documents/PGx/PharmCAT/tutorial/preprocessor/vcf_preprocess_utilities.py", line 515, in filter_pgx_variants
    updated_info = ';'.join(ref_info.append(fields[7])) if fields[7] != '.' else ';'.join(ref_info)
TypeError: can only join an iterable
```

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
```
# work under the current tutorial directory
PROJECT_DIR="$PWD"
cd "$PROJECT_DIR"

# get the latest VCF preprocessor script
wget https://github.com/PharmGKB/PharmCAT/releases/latest/pharmcat-preprocessor-<latest_version>.tar.gz
tar -xvf pharmcat-preprocessor-<latest_version>.tar.gz
VCF_PREPROCESS_SCRIPT=preprocessor/PharmCAT_VCF_Preprocess.py
# install the required python libraries
pip3 install -r preprocessor/PharmCAT_VCF_Preprocess_py3_requirements.txt
# reference PGx positions used by the PharmCAT
REF_PGX_VCF=preprocessor/pharmcat_positions.vcf.bgz

# outputs
PREPROCESSED_DIR=results/pharmcat_ready/
mkdir -p "$PREPROCESSED_DIR"

# input multi-sample VCF
TUTORIAL_VCF=data/PharmCAT_tutorial_get-rm_wgs_30x_grch38.vcf.bgz
# run the PharmCAT VCF preprocessor
python3 "$VCF_PREPROCESS_SCRIPT" \
  -vcf "$TUTORIAL_VCF" \
  -refVcf "$REF_PGX_VCF" \
  -o "$PREPROCESSED_DIR"
```

* **Please tell us about your environment:**
  
  - PharmCAT Version: 2.0.2
  - JDK Version: 17.0.5 (2022-10-18 LTS)
  - Environment: macOS

**Comment by markwoon** [comment]
This has been fixed in [2.0.3](https://github.com/PharmGKB/PharmCAT/releases/tag/v2.0.3).
