### ISSUE TITLE
Exception Error 

### ISSUE THREAD

**Issue by m-saleem** [PharmGKB/PharmCAT#12]
When I try using the tool, I get the following error. Please can you help me with this? 

java.lang.NullPointerException
	at org.pharmgkb.pharmcat.util.Ugt1a1AlleleMatcher.matchHaplotypes(Ugt1a1AlleleMatcher.java:77)
	at org.pharmgkb.pharmcat.util.Ugt1a1AlleleMatcher.makeLookupCalls(Ugt1a1AlleleMatcher.java:45)
	at org.pharmgkb.pharmcat.reporter.model.result.GeneReport.setDiplotypes(GeneReport.java:89)
	at org.pharmgkb.pharmcat.reporter.ReportContext.compileMatcherData(ReportContext.java:110)
	at org.pharmgkb.pharmcat.reporter.ReportContext.<init>(ReportContext.java:58)
	at org.pharmgkb.pharmcat.reporter.Reporter.analyze(Reporter.java:140)
	at org.pharmgkb.pharmcat.PharmCAT.execute(PharmCAT.java:163)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:86)

**Comment by whaleyr** [comment]
This should have been fixed in e48f2eee194338ed172cddc6114ef8b8c5789478. Let me know if it wasn't.
