### ISSUE TITLE
WSL2 Pharmcat Installation

### ISSUE THREAD

**Issue by DineshRavindraRaju** [PharmGKB/PharmCAT#133]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Not able to install it locally. I have cloned the pharmcat repo and tried to install with sudo make 

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

Updating data...
> Task :compileJava
> Task :processResources
> Task :classes

> Task :updateData
Saving messages to /mnt/f/open_source/ML_Projects/Pharmcare/team6/data/PharmCAT/src/main/resources/org/pharmgkb/pharmcat/reporter/messages.json
Downloading DPWG data...
Saving CPIC guidelines to /mnt/f/open_source/ML_Projects/Pharmcare/team6/data/PharmCAT/src/main/resources/org/pharmgkb/pharmcat/reporter/guidelines/cpic
Found 108 CPIC guidelines
Saving DPWG guidelines to /mnt/f/open_source/ML_Projects/Pharmcare/team6/data/PharmCAT/src/main/resources/org/pharmgkb/pharmcat/reporter/guidelines/dpwg
Found 55 DPWG guidelines
Saving CPIC phenotypes to /mnt/f/open_source/ML_Projects/Pharmcare/team6/data/PharmCAT/src/main/resources/org/pharmgkb/pharmcat/phenotype/cpic
Found 16 CPIC phenotypes
Saving DPWG phenotypes to /mnt/f/open_source/ML_Projects/Pharmcare/team6/data/PharmCAT/src/main/resources/org/pharmgkb/pharmcat/phenotype/dpwg
Found 14 DPWG phenotypes
Saving exemptions to /mnt/f/open_source/ML_Projects/Pharmcare/team6/data/PharmCAT/src/main/resources/org/pharmgkb/pharmcat/definition/alleles/exemptions.json
Generating allele definitions...
Query cache updated!  Saving cache file to /mnt/f/open_source/ML_Projects/Pharmcare/team6/data/PharmCAT/build/resources/main/org/pharmgkb/pharmcat/util/vcfQueryCache.json
Don't forget to save this file!
java.io.IOException: Docker run failed (125)
Unable to find image 'pcat:latest' locally
docker: Error response from daemon: pull access denied for pcat, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

        at org.pharmgkb.pharmcat.util.DockerRunner.runCmd(DockerRunner.java:98)
        at org.pharmgkb.pharmcat.util.DockerRunner.normalizeVcf(DockerRunner.java:39)
        at org.pharmgkb.pharmcat.util.VcfHelper.normalizeRepeats(VcfHelper.java:216)
        at org.pharmgkb.pharmcat.definition.model.DefinitionFile.translateVariantLocus(DefinitionFile.java:423)
        at org.pharmgkb.pharmcat.definition.model.DefinitionFile.doVcfTranslation(DefinitionFile.java:257)
        at org.pharmgkb.pharmcat.util.DataManager.transformAlleleDefinitions(DataManager.java:350)
        at org.pharmgkb.pharmcat.util.DataManager.main(DataManager.java:211)

> Task :updateData FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':updateData'.
> Process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
3 actionable tasks: 3 executed

* **What is the expected behavior?**

.

* **What is the motivation / use case for changing the behavior?**
.

* **Please tell us about your environment:**
  
  - PharmCAT Version: latest
  - JDK Version: [ JDK8 | OpenJDK | etc ] : java -version
  - Environment: [ Windows | macOS | Linux distro | etc ] wsl2 : Ubuntu

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by markwoon** [comment]
What are you trying to accomplish?

Your subject says "PharmCAT installation" but `make updateData` has nothing to do with installation.

Have you consulted https://pharmcat.org for documentation?

**Comment by DineshRavindraRaju** [comment]
Please accept my apologies. I was successful in running the pre-compiled JAR file. When i tried to run the application  I get the following errors  with positions.vcf.

python3 ../../PharmCAT/PharmCAT/preprocessor/pharmcat_vcf_preprocessor.py -vcf pharmcat_positions.vcf

java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "this.m_baseDir" is null
        at org.pharmgkb.pharmcat.Pipeline.<init>(Pipeline.java:101)
        at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:165)

So I tried checking the vcf file with the above pharmcat vcf preprocessor.py and got the faidx error.

Saving output to /mnt/f/open_source/ML_Projects/Pharmcare/team6/data/samples/23_and_me
Processing pharmcat_positions.vcf ...
[E::faidx_adjust_position] The sequence "chr4" not found
faidx_fetch_seq failed at chr4:8813117

**Comment by markwoon** [comment]
It looks like you are leaving out some steps.

Running `python3 ../../PharmCAT/PharmCAT/preprocessor/pharmcat_vcf_preprocessor.py -vcf pharmcat_positions.vcf` only runs the preprocessor and does not call java, which is where the error you are reporting comes from.

Please either list all the steps you using or provide a screenshot of the console.
