### ISSUE TITLE
2.8.1 DPYD: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2

### ISSUE THREAD

**Issue by hudja** [PharmGKB/PharmCAT#156]
Hi,

sorry, but I have bad news concerning DPYD again... I am using 2.8.1 PharmCat and 2.8.1 preprocessor.

```
java -jar pharmcat-2.8.1-all.jar -vcf test.vcf.gz -o ./
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at org.pharmgkb.pharmcat.haplotype.model.CombinationMatch.buildHaplotype(CombinationMatch.java:129)
	at org.pharmgkb.pharmcat.haplotype.model.CombinationMatch.merge(CombinationMatch.java:177)
	at org.pharmgkb.pharmcat.haplotype.DpydHapB3Matcher.updateHapB3Haplotype(DpydHapB3Matcher.java:252)
	at org.pharmgkb.pharmcat.haplotype.DpydHapB3Matcher.buildDiplotype(DpydHapB3Matcher.java:205)
	at org.pharmgkb.pharmcat.haplotype.DpydHapB3Matcher.mergePhasedDiplotypeMatch(DpydHapB3Matcher.java:198)
	at org.pharmgkb.pharmcat.haplotype.NamedAlleleMatcher.callDpyd(NamedAlleleMatcher.java:310)
	at org.pharmgkb.pharmcat.haplotype.NamedAlleleMatcher.call(NamedAlleleMatcher.java:202)
	at org.pharmgkb.pharmcat.Pipeline.call(Pipeline.java:233)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:166)
```

VCF body which produces an error. Phased data. Other sites are REFs.
```
chr1	97305364	.	C	T	.	.	.	GT	1|0
chr1	97515839	.	T	C	.	.	.	GT	1|0
chr1	97573863	.	C	T	.	.	.	GT	1|0
chr1	97579893	.	G	C	.	.	.	GT	1|0
```

Test VCF file.
https://www.dropbox.com/scl/fi/5cso1hdhz3fhypnlw9jp0/test.vcf.gz?rlkey=m4ik7mjx0897xi3q5prqbrkaq&dl=0

Thank you!

**Comment by markwoon** [comment]
I've got a fix for this. That included VCF simplifies things.  BTW, you can also just drag and drop files into GitHub to attach it to an issue (you may have to zip it up first).

Could you please try this out and see if you run into any more problems:
[pharmcat-2.8.1-1-ga29420a4-all.zip](https://github.com/PharmGKB/PharmCAT/files/12774027/pharmcat-2.8.1-1-ga29420a4-all.zip)

Unzip and use this instead of your existing `pharmcat-xxx-all.jar`.

If you don't find any more problems, I'll cut a new release.

Thanks.

**Comment by hudja** [comment]
Hi, it seems working fine now! Thank you for the quick response!
