### ISSUE TITLE
PharmCAT Annotation Error -- Triploid Genotypes

### ISSUE THREAD

**Issue by pbrennan-mvz** [PharmGKB/PharmCAT#167]
* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

Annotate step will not accept triploid genotypes

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

to reproduce the bug, run the command below with a triploid genotype in the test_pharmcat.tsv file.
java -jar scripts/pharmcat-2.8.3-all.jar -vcf test.hard-filtered.preprocessed.vcf.bgz -o results/coriell/pharmcat -po test_pharmcat.tsv -reporterJson

* **What is the expected behavior?**

PharmCAT would accept these genotypes and annotate them.

* **What is the motivation / use case for changing the behavior?**

We have some samples in our truth data set with *1/*2/*5 genotypes on CYP2D6.  For these samples, we cannot make a pharmcat report without manually altering the pangu _pharmcat.tsv file.

* **Please tell us about your environment:**
  
  - PharmCAT Version: 2.8.3
  - JDK Version: [ JDK8 | OpenJDK | etc ]
  - Environment: [ Windows | macOS | Linux distro | etc ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

Here is the command that is failing:

java -jar scripts/pharmcat-2.8.3-all.jar -vcf test.hard-filtered.preprocessed.vcf.bgz -o results/coriell/pharmcat -po test_pharmcat.tsv -reporterJson

Here is the error that is being produced:

org.pharmgkb.pharmcat.reporter.BadOutsideCallException: Line 1: Too many alleles specified in *1/*2/*5
        at org.pharmgkb.pharmcat.phenotype.model.OutsideCall.<init>(OutsideCall.java:69)
        at org.pharmgkb.pharmcat.phenotype.OutsideCallParser.parse(OutsideCallParser.java:52)
        at org.pharmgkb.pharmcat.Pipeline.call(Pipeline.java:282)
        at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:166)
~

**Comment by whaleyr** [comment]
The data sources PharmCAT uses have no annotations for triploid genotype calls. There is no way to annotate this apart from repeating the genotype call in the report with no other information.

Biologically, what are you saying when you give a triploid call like this? Are you indicating a third strand for the chromosome? Is there a second copy of the gene on one of the strands?

**Comment by katrinsangkuhl** [comment]
The attached file includes the CYP2D6 alleles (and their format) that when presented as part of a diplotype can be annotated with content based on the data sources PharmCAT uses.

 [CYP2D6_allele_functionality_reference.xlsx](https://github.com/PharmGKB/PharmCAT/files/13745533/CYP2D6_allele_functionality_reference.xlsx)

**Comment by markwoon** [comment]
Closing - no new input.
