### ISSUE TITLE
HAPB3 calling

### ISSUE THREAD

**Issue by diegomd90** [PharmGKB/PharmCAT#191]
Hello;

I'm running Pharmcat 2.6 on a Ubuntu OS

I'm having some issues regarding HAPB3 calling on some on my samples:

```
java.lang.IllegalStateException: Least function gene cannot have more than 1 diplotype: Reference/Reference; c.1129-5923C>G, c.1236G>A (HapB3)/c.1129-5923C>G, c.1236G>A (HapB3)
	at org.pharmgkb.pharmcat.haplotype.NamedAlleleMatcher.callDpyd(NamedAlleleMatcher.java:303)
	at org.pharmgkb.pharmcat.haplotype.NamedAlleleMatcher.call(NamedAlleleMatcher.java:196)
	at org.pharmgkb.pharmcat.Pipeline.call(Pipeline.java:235)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:166)
```

I have never seen this error before, can you help me?

**Comment by BinglanLi** [comment]
Please use the latest PharmCAT release following the [link](https://github.com/PharmGKB/PharmCAT/releases/latest). And please feel free to let us know if the issue still happens for you.

**Comment by markwoon** [comment]
Please re-open this issue if this is a problem with a current release.
