### ISSUE TITLE
Problem running pharmcat-0.6.0-all.jar (BUG?)

### ISSUE THREAD

**Issue by CarlosGAH** [PharmGKB/PharmCAT#20]
Hi, i have tried to use the release version 0.6.0 of pharmcat with the sample vcf that you can download, but i've got this error:
First i downloaded the .jar from the release page.
When i use the command alone i get this
java -jar /home/usuario/tools_java/Pharmacat/pharmcat-0.6.0-all.jar
Missing required options: vcf, o

usage: PharmCAT
 -a,--astrolabe-file <a>    path to astrolabe result file (TSV)
 -f,--output-file <f>       the base name used for ouput file names (will
                            add file extensions), will default to same
                            value as call-file if not specified
 -g,--guidelines-dir <n>    directory of guideline annotations (JSON
                            files)
 -h,--help                  print this message
 -j,--write-report-json     flag to write a JSON file of the data used to
                            populate the final report
 -k,--keep-matcher-files    flag to keep the intermediary matcher output
                            files
 -na,--alleles-dir <l>      directory of named allele definitions (JSON
                            files)
 -o,--output-dir <o>        directory to output to
 -v,--verbose               enable verbose output
 -vcf,--sample-file <vcf>   input call file (VCF)

The normal output, but when i try to use it with a vcf:

java -jar /home/usuario/tools_java/Pharmacat/pharmcat-0.6.0-all.jar -vcf pharmcat.v0.6.0.vcf -o prueba_pharma
com.google.gson.JsonSyntaxException: Apr 12, 2016 12:00:00 AM
	at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:74)
	at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:59)
	at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at org.pharmgkb.pharmcat.util.DataSerializer.deserializeDefinitionsFromJson(DataSerializer.java:59)
	at org.pharmgkb.pharmcat.haplotype.DefinitionReader.readFile(DefinitionReader.java:103)
	at org.pharmgkb.pharmcat.haplotype.DefinitionReader.read(DefinitionReader.java:90)
	at org.pharmgkb.pharmcat.PharmCAT.<init>(PharmCAT.java:123)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:79)
Caused by: java.text.ParseException: Failed to parse date ["Apr 12, 2016 12:00:00 AM']: Invalid number: Apr 
	at com.google.gson.internal.bind.util.ISO8601Utils.parse(ISO8601Utils.java:274)
	at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:72)
	... 11 more
Caused by: java.lang.NumberFormatException: Invalid number: Apr 
	at com.google.gson.internal.bind.util.ISO8601Utils.parseInt(ISO8601Utils.java:311)
	at com.google.gson.internal.bind.util.ISO8601Utils.parse(ISO8601Utils.java:129)
	... 12 more
The vcf is the one in the release page and this is my setting

  - PharmCAT Version: 0.6.0 release
  - JDK Version: openjdk version "10.0.2" 2018-07-17
                          OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
                          OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
  - Environment: Linux Ubuntu 18.04

Thanks for your time and work!

**Comment by CarlosGAH** [comment]
I have tried to use the same jar in other computer and worked perfectly, so it must be a problem within my own computer. Thanks for your time and sorry for the incovenience.
