### ISSUE TITLE
GenePhenotype.java NullPointerException

### ISSUE THREAD

**Issue by a113n** [PharmGKB/PharmCAT#27]
I am trying to use a GSAv2.0 VCF generated by the Illumina GTCtoVCF software. It seems like Pharmcat fails to generate diplotypes from the file.

* **What is the current behavior?**

java.lang.NullPointerException
	at org.pharmgkb.pharmcat.definition.model.GenePhenotype.makePhenoPair(GenePhenotype.java:89)
	at org.pharmgkb.pharmcat.definition.model.GenePhenotype.makePhenotype(GenePhenotype.java:107)
	at org.pharmgkb.pharmcat.reporter.DiplotypeFactory.fillDiplotype(DiplotypeFactory.java:127)
	at org.pharmgkb.pharmcat.reporter.DiplotypeFactory.makeDiplotype(DiplotypeFactory.java:104)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.pharmgkb.pharmcat.reporter.DiplotypeFactory.makeDiplotypes(DiplotypeFactory.java:65)
	at org.pharmgkb.pharmcat.reporter.model.result.GeneReport.setDiplotypes(GeneReport.java:94)
	at org.pharmgkb.pharmcat.reporter.ReportContext.compileMatcherData(ReportContext.java:143)
	at org.pharmgkb.pharmcat.reporter.ReportContext.<init>(ReportContext.java:87)
	at org.pharmgkb.pharmcat.reporter.Reporter.analyze(Reporter.java:148)
	at org.pharmgkb.pharmcat.PharmCAT.execute(PharmCAT.java:164)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:86)

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - PharmCAT Version: 0.7.0-33-gf1a9954
  - JDK Version: OpenJDK 1.8.0_231
  - Environment: macOS 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by whaleyr** [comment]
@a113n Can you confirm that you're following the [VCF requirements](https://github.com/PharmGKB/PharmCAT/wiki/VCF-Requirements)?

If so, do you have a synthetic (**no real-life subject information**) example of a GSAv2.0 VCF file that I could use for testing? It's hard to troubleshoot without one.

**Comment by muzic194** [comment]
I have the same problem. I have found that getHaplotypes() in GenePhenotype.java returns null because there is no "haplotype" field defined in `definition/gene.phenotypes.json` for NUDT15 gene (possibly others). 

My command: 

```
java -jar pharmcat.jar -vcf 495.vcf -o sampledir -j pharmcat.json -k -f 495_pgx
```

Here's 495.vcf that causes this error:

https://gist.github.com/muzic194/5a8db74833094531e5721f7b63f392b4

Could you please try to fix it? Thank you!

**Comment by whaleyr** [comment]
NUDT15 is in the gene.phenotypes.json file on the `main` branch but that hasn't been officially released yet. Feel free to use it but know that the contents of that file may change before it gets put into a release.
