### ISSUE TITLE
Function mismatch for CYP2D6 *1 > Normal Function != null while running analysis

### ISSUE THREAD

**Issue by NTNguyen13** [PharmGKB/PharmCAT#30]
* **Do you want to request a *feature* or report a *bug*?**
I want to report a bug

* **What is the current behavior?**
Error Function mismatch for CYP2D6 *1 > Normal Function != null while running analysis
Full Error log
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
>>> WARNING: This is pre-release software, not for production use <<<
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
org.pharmgkb.pharmcat.UnexpectedStateException: Function mismatch for CYP2D6 *1 > Normal Function != null
        at org.pharmgkb.pharmcat.definition.PhenotypeMap.lambda$new$0(PhenotypeMap.java:50)
        at java.util.ArrayList.forEach(ArrayList.java:1251)
        at org.pharmgkb.pharmcat.definition.PhenotypeMap.<init>(PhenotypeMap.java:37)
        at org.pharmgkb.pharmcat.reporter.ReportContext.<init>(ReportContext.java:64)
        at org.pharmgkb.pharmcat.reporter.Reporter.analyze(Reporter.java:140)
        at org.pharmgkb.pharmcat.PharmCAT.execute(PharmCAT.java:164)
        at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:86)
```

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
I used multiple variant callers to call the variants on a WGS sample, with respect to a PGx bed files. Then I run pharmcat and encounter this problem on all vcf from different callers (HaplotypeCaller, VarDict, FreeBayes, DeepVariant)

What have gone wrong in my case? Thank you

* **Please tell us about your environment:**
  
  - PharmCAT Version: 0.7.0
  - JDK Version: OpenJDK 1.8
  - Environment: Ubuntu 16.04

**Comment by NTNguyen13** [comment]
dive a bit deeper, when I remove the chr22 from my bed file, it works. I test the same bed file against NA12878 sample aligned by NYGC, it workds. The only different is that my bam file is aligned without ALT-handling while the NA12878 has it.

**Comment by NTNguyen13** [comment]
I found 2 variants causing the problem:
chr22	42126611	.	C	G	510.64	.	AC=1;AF=0.5;AN=2;BaseQRankSum=1.59;DP=37;ExcessHet=3.0103;FS=1.271;MLEAC=1;MLEAF=0.5;MQ=59.57;MQRankSum=-1.603;QD=14.18;ReadPosRankSum=0.123;SOR=0.465	GT:AD:DP:GQ:PL	0/1:21,15:37:99:518,0,723
chr22	42130692	.	G	A	1203.64	.	AC=1;AF=0.5;AN=2;BaseQRankSum=1.64;DP=49;ExcessHet=3.0103;FS=0;MLEAC=1;MLEAF=0.5;MQ=60;MQRankSum=0;QD=26.75;ReadPosRankSum=1.15;SOR=0.749	GT:AD:DP:GQ:PL	0/1:12,33:47:99:1211,0,332

**Comment by definitivequestion** [comment]
I get a similar error as given below:
org.pharmgkb.pharmcat.UnexpectedStateException: Function mismatch for CYP2D6 *10 > Decreased Function != null
	at org.pharmgkb.pharmcat.definition.PhenotypeMap.lambda$new$0(PhenotypeMap.java:50)
	at java.util.ArrayList.forEach(ArrayList.java:1251)
	at org.pharmgkb.pharmcat.definition.PhenotypeMap.<init>(PhenotypeMap.java:37)
	at org.pharmgkb.pharmcat.reporter.ReportContext.<init>(ReportContext.java:64)
	at org.pharmgkb.pharmcat.reporter.Reporter.analyze(Reporter.java:140)
	at org.pharmgkb.pharmcat.PharmCAT.execute(PharmCAT.java:164)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:86)

**Comment by tizatt** [comment]
I also got a similar error.  This was using a DeepVariant vcf :

```
org.pharmgkb.pharmcat.UnexpectedStateException: Function mismatch for CYP2D6 *3 > No Function != null
	at org.pharmgkb.pharmcat.definition.PhenotypeMap.lambda$new$0(PhenotypeMap.java:50)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.pharmgkb.pharmcat.definition.PhenotypeMap.<init>(PhenotypeMap.java:37)
	at org.pharmgkb.pharmcat.reporter.ReportContext.<init>(ReportContext.java:64)
	at org.pharmgkb.pharmcat.reporter.Reporter.analyze(Reporter.java:140)
	at org.pharmgkb.pharmcat.PharmCAT.execute(PharmCAT.java:164)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:86)
```

**Comment by markwoon** [comment]
Please try again with the latest version.  If this is still a problem, please open a new issue.
