### ISSUE TITLE
Error when providing path to directory containing allele definitions

### ISSUE THREAD

**Issue by kvergy** [PharmGKB/PharmCAT#44]
* **Do you want to request a *feature* or report a *bug*?**

*bug*

* **What is the current behavior?***
 
I have an eror, when I try to use pharmcat with argument -na (path to definitions dir):
```bash
java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.pharmgkb.common.io.util.CliHelper.getValidDirectory(CliHelper.java:217)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:71)
```

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
At first, I tried to use path to the directory with my custom exemptions.json file and default genes json files.

`java -jar /home/kvergy/pharmcat/pharmcat-0.7.1-all.jar -na /home/kvergy/CYP/test/2C19 -vcf chip_hg38.vcf -o .`

And I have an error:
```bash
java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.pharmgkb.common.io.util.CliHelper.getValidDirectory(CliHelper.java:217)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:71)
```
Then I tried to give `-na` argument using the path to the default directory from the source code (https://github.com/PharmGKB/PharmCAT/releases/tag/v0.7.1):

`java -jar pharmcat-0.7.1-all.jar -vcf chip_hg38.vcf -o . -na /home/kvergy/CYP/test/git/PharmCAT-0.7.1/src/main/resources/org/pharmgkb/pharmcat/definition/alleles/`

And I have the same error.

* **What is the expected behavior?**
Custom exemptions.json are used instead of default files.

* **What is the motivation / use case for changing the behavior?**

I want to use my custom allele definitions.

* **Please tell us about your environment:**
  
  - PharmCAT Version: pharmcat-0.7.1
  - JDK Version:  openjdk version "1.8.0_275"
  - Environment: Linux 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by markwoon** [comment]
Please try again with the latest version.  If this is still a problem, please open a new issue.
