### ISSUE TITLE
error in NUDT15_translation.json causing PharmCAT to fail

### ISSUE THREAD

**Issue by BinglanLi** [PharmGKB/PharmCAT#46]
* **Do you want to request a *feature* or report a *bug*?**

*bug*

* **What is the current behavior?**

PharmCAT reports an error pertinent to a _NUDT15_ variant.

> "java.lang.IllegalStateException: Not an deletion: G >GGGAGTC @ g.48037796delGAGTCG
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
> 	at org.pharmgkb.pharmcat.haplotype.SampleAllele.convertDeletion(SampleAllele.java:186)
> 	at org.pharmgkb.pharmcat.haplotype.SampleAllele.forVariant(SampleAllele.java:133)
> 	at org.pharmgkb.pharmcat.haplotype.MatchData.<init>(MatchData.java:78)
> 	at org.pharmgkb.pharmcat.haplotype.NamedAlleleMatcher.initializeCallData(NamedAlleleMatcher.java:208)
> 	at org.pharmgkb.pharmcat.haplotype.NamedAlleleMatcher.call(NamedAlleleMatcher.java:177)
> 	at org.pharmgkb.pharmcat.PharmCAT.execute(PharmCAT.java:145)
> 	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:81)"

The root of the issue is likely in the NUDT15_translation.json.

* **Please tell us about your environment:**
  
  - PharmCAT Version: v0.8.0
  - JDK Version: 
  - Environment: Unix

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

### Issue 1 - delGAGTCG of rs746071566

> \# in NUDT15_translation.json
>     {
>       "chromosome": "chr13",
>       "position": 48037796,  ------> 48037783 (including the anchoring G before the delGAGTCG) (without the anchoring G, the del**G**AGTCG starts at 48037784)
>       "rsid": "rs746071566",
>       "chromosomeHgvsName": "g.48037796delGAGTCG",
>       "geneHgvsName": "g.5230delGAGTCG",
>       "proteinNote": "G17_V18del",
>       "resourceNote": "50delGAGTCG",
>       "type": "DEL",
>       "referenceRepeat": null
>     },

And in the .json, the corresponding REF and ALT alleles in the sections **variantAlleles** and **namedAlleles** are different from what's presented above in the **variants** section. I think it should be "delGAGTCG", instead of "delGGAGTC", but an expert's opinion may be needed here.

In the PharmCAT's PGx position VCF, in my opinion, the corresponding record should be 

> chr13   48037783        rs746071566     GGAGTCG G       .       PASS    PX=NUDT15:*1[19]isGGAGTC,NUDT15:*9[1]isdelGGAGTC        GT      ./

### Issue 2 - differences between PharmVar and dbSNP for insGAGTCG of rs746071566.

On the same rs746071566, but a different type of SV (now insertion, instead of del in the issue 1). 

>     {
>       "chromosome": "chr13",
>       "position": 48037801,
>       "rsid": "rs746071566",
>       "chromosomeHgvsName": "g.48037801_48037802insGAGTCG",
>       "geneHgvsName": "g.5235_5326insGAGTCG",
>       "proteinNote": "V18_V19insGV",
>       "resourceNote": "55_56insGAGTCG",
>       "type": "INS",
>       "referenceRepeat": null
>     },

- This insertion is also part of rs746071566 in the view of dbSNP, which means it has the same genomic position as delGAGTCG (chr13:48037783). 
- However, PharmVar considers this insertion "55_56insGAGTCG" to start at the position 48037801, different from dbSNP. 

The REF and ALT alleles are correctly presented in the PharmCAT position VCF, despite the issue with its specific genomic position.

I am not sure what to do with the second issue since it relates to how PharmVar choose to present this structural variation.

**Comment by masger** [comment]
I'm also experiencing this issue with PharmCAT v3.0.1.
Environment:

PharmCAT version: 3.0.1
Array: Illumina GSA-PGx (InfiniumGSAPGx48 v4.0)
VCF generation: DRAGEN Array VCF Generator
Environment: HPC

The problem:
My VCF contains two records at chr13:48037782:
chr13   48037782   IlmnSeq_rs554405994   A   AGGAGTC   .   PASS   .   GT   0/0
chr13   48037782   ilmnseq_rs61746486... A   C         .   PASS   .   GT   0/0
The preprocessor crashes with:
KeyError: ('A', 'AGGAGTC')
Even after filtering out the A>C SNV, PharmCAT still fails because it expects REF=AGGAGTC ALT=A (deletion format) but my array outputs REF=A ALT=AGGAGTC (insertion format).

pypgx does handle this. 

Workaround:
Currently filtering out position chr13:48037782 entirely, which works for 0/0 samples but would lose information for carriers of this variant.
Is there a plan to update PharmCAT to handle both variant representations for rs746071566?

Want me to adjust anything?

**Comment by whaleyr** [comment]
@masger are you using the preprocessor?

**Comment by whaleyr** [comment]
I'm using the following test VCF with the positions you specify:
```
##fileformat=VCFv4.2
##source=PharmCAT test (testDuplicateEntrySecondIsBad)
##fileDate=2026-01-15T13:21:36.242229-08:00
##contig=<ID=chr13,assembly=GRCh38.p14,species="Homo sapiens">
##FILTER=<ID=PASS,Description="All filters passed">
##INFO=<ID=PX,Number=.,Type=String,Description="Gene">
##INFO=<ID=POI,Number=0,Type=Flag,Description="Position of Interest but not part of an allele definition">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	PharmCAT
chr13	48037748	rs769369441	T	C	.	PASS	PX=NUDT15	GT	0/0
chr13	48037749	.	G	C	.	PASS	PX=NUDT15	GT	0/0
chr13   48037782 IlmnSeq_rs554405994 A AGGAGTC . PASS . GT 0/0
chr13   48037782 ilmnseq_rs61746486 A C . PASS . GT 0/0
chr13	48037798	rs186364861	G	A	.	PASS	PX=NUDT15	GT	0/0
chr13	48037825	rs777311140	C	CGCGG	.	PASS	PX=NUDT15	GT	0/0
chr13	48037834	rs1202487323	C	T	.	PASS	PX=NUDT15	GT	0/0
chr13	48037847	rs766023281	G	C	.	PASS	PX=NUDT15	GT	0/0
chr13	48037849	.	A	G	.	PASS	PX=NUDT15	GT	0/0
chr13	48037885	rs1950545307	G	A	.	PASS	PX=NUDT15	GT	0/0
chr13	48037902	rs149436418	C	G	.	PASS	PX=NUDT15	GT	0/0
chr13	48040977	rs1457579126	GA	G	.	PASS	PX=NUDT15	GT	0/0
chr13	48041103	rs761191455	T	TG	.	PASS	PX=NUDT15	GT	0/0
chr13	48041113	rs1368252918	G	T	.	PASS	PX=NUDT15	GT	0/0
chr13	48045690	rs768324690	C	G	.	PASS	PX=NUDT15	GT	0/0
chr13	48045714	rs1185228044	G	C	.	PASS	PX=NUDT15	GT	0/0
chr13	48045719	rs116855232	C	T	.	PASS	PX=NUDT15	GT	0/0
chr13	48045720	rs147390019	G	A	.	PASS	PX=NUDT15	GT	0/0
chr13	48045771	rs139551410	T	A	.	PASS	PX=NUDT15	GT	0/0
```

I'm using the latest PharmCAT docker container (3.1.1)

```sh
docker run -v .:/pharmcat/data pgkb/pharmcat pharmcat_pipeline /pharmcat/data/test.vcf
```

It runs with the data and I believe gives the output you expect (with warnings)

```
PharmCAT version: 3.1.1



Processing /pharmcat/data/test.vcf ...
  * WARNING: "chr13:48037782 REF=A ALT=C" does not match PharmCAT expectation of ALT at "chr13:48037782 REF=AGGAGTC ALT=A"
  * WARNING: "chr13:48037782 REF=A ALT=C" does not match PharmCAT expectation of ALT at "chr13:48037782 REF=A ALT=AGGAGTC"
Adding back non-PGx variants at PGx positions...
* Cataloging 1184 missing positions in /pharmcat/data/test.missing_pgx_var.vcf

Running PharmCAT...
Checking files...
* Found 1 VCF file
Saving named allele matcher JSON results to /pharmcat/data/test.match.json
Saving phenotyper JSON results to /pharmcat/data/test.phenotype.json
Saving reporter HTML results to /pharmcat/data/test.report.html

Done.
```

rs554405994 has been merged into rs746071566. rs61746486 is a SNP that's 1bp upstream from rs746071566. These should be normalized to the representation for rs746071566 which is what PharmCAT uses. The preprocessor does this when running the whole pharmcat pipeline.

**Comment by markwoon** [comment]
@masger A sample VCF exhibiting this problem would help, along with the command you're using that's causing the problem.

**Comment by masger** [comment]
Yes I have used the preprocessor. I have tried to make a reproducible sample (attached). The sample @whaleyr sent also worked for me. 

I've experienced inconsistent behavior that appears related to caching or intermediate files. If I change the name to a new name then it stops working. 

A sample VCF attached. 
[sample_clean_new.vcf.gz](https://github.com/user-attachments/files/24671205/sample_clean_new.vcf.gz)


```
pharmcat_vcf_preprocessor \
  -vcf test/sample_clean_new.vcf.gz \
  -GCA_000001405.15_GRCh38_no_alt_analysis_set_maskedGRC_exclusions.fasta \
  -refVcf temp/pharmcat_positions.vcf.bgz \
  -o output_clean_sample/ \
  -v
```

```
cand@login-01 micand]$ pharmcat_vcf_preprocessor \
PharmCAT VCF Preprocessor version: 3.0.1
Reading samples from test/sample_clean_new.vcf.gz ...
Using reference FASTA at GCA_000001405.15_GRCh38_no_alt_analysis_set_maskedGRC_exclusions.fasta
Saving output to output_clean_sample

Reading samples from test/sample_clean_new.vcf.gz ...
Processing test/sample_clean_new.vcf.gz ...
* Extracting PGx regions and normalizing chromosome names
* Normalizing VCF
  * Retaining PGx positions, regardless of alleles
* Updating VCF header and PGx position annotations
  * WARNING: "chr13:48037782 REF=A ALT=C" does not match PharmCAT expectation of ALT at "chr13:48037782 REF=AGGAGTC ALT=A"
  * WARNING: "chr13:48037782 REF=A ALT=C" does not match PharmCAT expectation of ALT at "chr13:48037782 REF=A ALT=AGGAGTC"
Traceback (most recent call last):
  File "tools/eb/v5.0/amd/software/PharmCAT/3.0.1-GCC-13.3.0/bin/pharmcat_vcf_preprocessor", line 231, in <module>
    results = pcat.preprocess(pharmcat_positions_vcf=m_pharmcat_positions_vcf,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tools/eb/v5.0/amd/software/PharmCAT/3.0.1-GCC-13.3.0/pcat/preprocess.py", line 71, in preprocess
    multisample_vcf = _preprocess(pharmcat_positions_vcf, reference_genome, regions_to_retain, custom_regions,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tools/eb/v5.0/amd/software/PharmCAT/3.0.1-GCC-13.3.0/pcat/preprocess.py", line 150, in _preprocess
    pgx_variants_vcf: Path = util.extract_pgx_variants(pharmcat_positions_vcf, reference_genome, normalized_vcf,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tools/eb/v5.0/amd/software/PharmCAT/3.0.1-GCC-13.3.0/pcat/utilities.py", line 1066, in extract_pgx_variants
    ref_pos_dynamic[input_chr_pos].pop(input_ref_alt)
KeyError: ('A', 'AGGAGTC')

```

**Comment by markwoon** [comment]
It looks like you are using a custom reference genome and a custom set of positions.

I believe you should be using `-refFna` instead of `-G`.

I'm sorry, but I'm unable to help you debug this as it could be the result of your custom dataset.


> I've experienced inconsistent behavior that appears related to caching or intermediate files. If I change the name to a new name then it stops working.

Could you be more specific?  Change the name of what?

If would like to hear more about this, and would appreciate it if you could open a new issue about it.  Please describe what you have done to see this inconsistent behavior, and exactly what is inconsistent.

**Comment by markwoon** [comment]
Closing this issue as the original problem reported by Binglan has been resolved.

@masger Feel free to open a new issue if you wish, but if you're using custom reference genome and positions, we really can't help you out.
