### ISSUE TITLE
Issue when running on WGS vcf file

### ISSUE THREAD

**Issue by anh151** [PharmGKB/PharmCAT#62]
* **Do you want to request a *feature* or report a *bug*?**
Report a bug maybe

* **What is the current behavior?**
I am able to get pharmcat to execute properly with an array vcf file, but I can't replicate the same behavior for a WGS vcf file using the exact same command. I tried to follow the traceback but was unsuccessful. 

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
```
output_vcf = f"{bucket}/hail/1111111_wgs.vcf.gz"
vcf_file_compressed = "1111111_wgs.vcf.gz"
vcf_file = "111111_wgs.vcf"
!gsutil cp {output_vcf} ./
!gunzip {vcf_file_compressed}
output_file = output + "1111111_wgs.json"
!java -cp {pharmcat} org.pharmgkb.pharmcat.phenotype.Phenotyper -vcf {vcf_file} -f {output_file}
```
```
Exception in thread "main" java.lang.IllegalArgumentException: Number of keys does not match number of values
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at org.pharmgkb.parser.vcf.model.VcfSample.<init>(VcfSample.java:28)
	at org.pharmgkb.parser.vcf.VcfParser.parseNextLine(VcfParser.java:239)
	at org.pharmgkb.parser.vcf.VcfParser.parse(VcfParser.java:127)
	at org.pharmgkb.pharmcat.haplotype.VcfReader.read(VcfReader.java:117)
	at org.pharmgkb.pharmcat.haplotype.VcfReader.<init>(VcfReader.java:59)
	at org.pharmgkb.pharmcat.haplotype.NamedAlleleMatcher.buildVcfReader(NamedAlleleMatcher.java:121)
	at org.pharmgkb.pharmcat.haplotype.NamedAlleleMatcher.call(NamedAlleleMatcher.java:162)
	at org.pharmgkb.pharmcat.phenotype.Phenotyper.main(Phenotyper.java:72)
Total elapsed time in seconds: 1.8486080169677734
```

* **Please tell us about your environment:**
  
  - PharmCAT Version: 0.8
  - JDK Version:
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
  - Environment: linux

**Comment by markwoon** [comment]
This error happens when the `FORMAT` column and the sample column in the VCF do not have the same number of elements.

For example:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
chr1	97078987	rs114096998	G	T	.	PASS	.	GT	0/0
chr1	97078987	rs114096998	G	T	.	FAIL	.	GT:GQ	0/0
chr1	97078987	rs114096998	G	T	.	FAIL	.	.	0/0
```

The first line is correct (1 entry in format, 1 entry in sample).
The second line fails because there are 2 entries in format, 1 entry in sample.
The third line fails because there are 0 entries in format, 1 entry in sample.

I'm closing this issue for now.  If this is not the case, please reopen with a sample of the VCF data containing the problem.  Please make sure the VCF data is anonymized.

FYI, we just released 1.0 and encourage you to update to the latest version.
