### ISSUE TITLE
JNI Error

### ISSUE THREAD

**Issue by joseph-yclam** [PharmGKB/PharmCAT#81]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Running into a JNI error despite having downloaded the appropriate Java environments and version on the anaconda server. It reads as:
`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/pharmgkb/pharmcat/PharmCAT has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
`

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
1. Downloaded latest version of PharmCAT (v1.3.0) onto local computer and used WinSCP to transfer the folder into a remote server
2. Created an anaconda environment named "PharmEnv" which I installed all the prerequisites.
3. This includes updating the java version

* **What is the expected behavior?**
When running `java -jar "/localhome/PharmCAT-1.2.0/lib/pharmcat-1.2.0-all.jar" -vcf pharmcat_positions.vcf -o test_outdir`, using the test data it should work.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - PharmCAT Version: v1.3.0
  - JDK Version: JDK8 |OpenJDK
  - Environment: Anaconda environment on Linux server

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)
* 
I tried using the following link to solve the JNI error and used the java command to see if I had the appropriate version: https://stackoverflow.com/questions/22381202/a-jni-error-has-occurred-please-check-your-installation-and-try-again-in-eclips. I confirmed that I was using the correct Java version in my anaconda environment on a separate computational server but still am unable to get the test command to work?

**Comment by whaleyr** [comment]
It looks like you're trying to run with JDK8. Can you try again with JDK14? [JDK14 is a requirement for PharmCAT.](https://github.com/PharmGKB/PharmCAT/wiki/Running-PharmCAT#requirements)

**Comment by joseph-yclam** [comment]
Hi
