### ISSUE TITLE
Preprocessor fails

### ISSUE THREAD

**Issue by KarlKeat** [PharmGKB/PharmCAT#94]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
```
Processing PMBB-45k-merged_chr10.vcf.gz
Traceback (most recent call last):
  File "/home/karlkeat/group/personal/karl/PharmCAT/src/scripts/preprocessor/PharmCAT_VCF_Preprocess.py", line 219, in <module>
    run(args)
  File "/home/karlkeat/group/personal/karl/PharmCAT/src/scripts/preprocessor/PharmCAT_VCF_Preprocess.py", line 138, in run
    vcf_pgx_regions = util.extract_regions_from_multiple_files(bcftools_path, tabix_path, bgzip_path, input_list,
  File "/project/ritchie07/personal/karl/PharmCAT/src/scripts/preprocessor/vcf_preprocess_utilities.py", line 315, in extract_regions_from_multiple_files
    single_file = extract_regions_from_single_file(bcftools_path, tabix_path, line, ref_pgx,
  File "/project/ritchie07/personal/karl/PharmCAT/src/scripts/preprocessor/vcf_preprocess_utilities.py", line 244, in extract_regions_from_single_file
    ref_pgx_regions = df_ref_pgx_pos.groupby(['CHROM'])['POS'].agg(_get_vcf_pos_min_max).reset_index()
  File "/appl/python-3.8/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 287, in aggregate
    return self._python_agg_general(func, *args, **kwargs)
  File "/appl/python-3.8/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1481, in _python_agg_general
    result = self.grouper.agg_series(obj, f)
  File "/appl/python-3.8/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 981, in agg_series
    result = self._aggregate_series_pure_python(obj, func)
  File "/appl/python-3.8/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 1005, in _aggregate_series_pure_python
    res = func(group)
  File "/appl/python-3.8/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1467, in <lambda>
    f = lambda x: func(x, *args, **kwargs)
  File "/project/ritchie07/personal/karl/PharmCAT/src/scripts/preprocessor/vcf_preprocess_utilities.py", line 181, in _get_vcf_pos_min_max
    return '-'.join([str(min(positions) - flanking_bp), str(max(positions) + flanking_bp)])
ValueError: min() arg is an empty sequence
```

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
```
module load htslib
module load bcftools

SCRIPT_PATH="/home/karlkeat/group/personal/karl/PharmCAT/src/scripts/preprocessor/PharmCAT_VCF_Preprocess.py"
INPUT_PATH="/project/ritchie20/projects/PMBB/PharmCAT/PMBB-merged-2020/preprocess_inputs.txt"
REF_PATH="/home/karlkeat/group/personal/karl/PharmCAT/input_files/GCA_000001405.15_GRCh38_full_analysis_set.fna"
PGX_PATH="/home/karlkeat/group/personal/karl/PharmCAT/pharmcat_positions.vcf.bgz"
OUT_DIR="/project/ritchie20/projects/PMBB/PharmCAT/PMBB-merged-2020/preprocess_out"

python3 $SCRIPT_PATH --input_list $INPUT_PATH --ref_seq $REF_PATH --ref_pgx_vcf $PGX_PATH --output_folder $OUT_DIR
```

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - PharmCAT Version: 1.5.1
  - JDK Version: Python 3.8
  - Environment: CentOS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

These same VCF files worked with previous versions of the preprocessor (last used around PharmCAT 1.0, so something broke between now and then).

**Comment by whaleyr** [comment]
@BinglanLi check this out when you get a minute.

**Comment by KarlKeat** [comment]
Seems to have been an issue with the cluster I was running it on using the wrong python interpreter. Not sure why it didn't give an ImportError, but the issue seems to be resolved.
